name: Yggdrasil
version: ${project.version}
main: tk.fridtjof.yggdrasil.Yggdrasil
api-version: 1.16
authors: [Fridtjof_DE]
description: An essential plugin
website: https://www.fridtjof.tk/

commands:
  monitor:
    description: Monitors server stats.
  head:
    description: Gets a player's head.
  msg:
    description: Sends a message to player.
  setspawn:
    description: Sets the spawn.
  spawn:
    description: Send the player to the spawn.
  yggdrasil:
    description: Some Yggdrasil commands.

permissions:
  yggdrasil.cmd.monitor:
    description: Grants permission to use the /monitor command!
  yggdrasil.signs.color_codes:
    description: Grants permission to use color codes on signs!
  yggdrasil.signs.formatting_codes:
    description: Grants permission to use formatting codes on signs!
  yggdrasil.cmd.head:
    description: Gets a player's head.
  yggdrasil.cmd.setspawn:
    description: Sets the spawn.
  yggdrasil.cmd.spawn:
    description: Send the player to the spawn.
  yggdrasil.reload:
    description: Reloads the plugin.