name: Yggdrasil
version: ${project.version}
main: tk.fridtjof.yggdrasil.Yggdrasil
api-version: 1.16
authors: [Fridtjof_DE]
description: An essential plugin
website: https://www.fridtjof.tk/
depend: [PuddingAPI]

commands:
  monitor:
    description: Monitors server stats.
  head:
    description: Gets a player's head.
  msg:
    description: Sends a message to player.
  tell:
    description: Sends a message to player.
  whisper:
    description: Sends a message to player.
  setspawn:
    description: Sets the spawn.
  spawn:
    description: Send the player to the spawn.
  yggdrasil:
    description: Some Yggdrasil commands.
  heal:
    description: Heal.
  day:
    description: Sets time to day.
  night:
    description: Sets time to night.
  noon:
    description: Sets time to noon.
  midnight:
    description: Sets time to midnight.
  gm:
    description: Set gamemode.
  gamemode:
    description: Set gamemode.
  fly:
    description: Toggle fly.
  speed:
    description: Set speed.

permissions:
  yggdrasil.cmd.monitor:
    description: Grants permission to use the /monitor command!
  yggdrasil.signs.color_codes:
    description: Grants permission to use color codes on signs!
  yggdrasil.signs.formatting_codes:
    description: Grants permission to use formatting codes on signs!
  yggdrasil.cmd.head:
    description: Gets a player's head.
  yggdrasil.cmd.setspawn:
    description: Sets the spawn.
  yggdrasil.cmd.spawn:
    description: Sends the player to the spawn.
  yggdrasil.cmd.spawn.others:
    description: Sends a player to the spawn.
  yggdrasil.reload:
    description: Reloads the plugin.
  yggdrasil.heal:
    description: Heal.
  yggdrasil.cmd.heal.others:
    description: Heal others.
  yggdrasil.chat.color_codes:
    description: Allows the user to user colors in chat.
  yggdrasil.chat.formatting_codes:
    description: Allows the user to user formatting codes in chat.
  yggdrasil.cmd.gm.0:
    description: /gm 0
  yggdrasil.cmd.gm.0.others:
    description: /gm 0 others
  yggdrasil.cmd.gm.1:
    description: /gm 1
  yggdrasil.cmd.gm.1.others:
    description: /gm 1 others
  yggdrasil.cmd.gm.2:
    description: /gm 2
  yggdrasil.cmd.gm.2.others:
    description: /gm 2 others
  yggdrasil.cmd.gm.3:
    description: /gm 3
  yggdrasil.cmd.gm.3.others:
    description: /gm 3 others
  yggdrasil.cmd.day:
    description: Sets time to day.
  yggdrasil.cmd.night:
    description: Sets time to night.
  yggdrasil.cmd.noon:
    description: Sets time to noon.
  yggdrasil.cmd.midnight:
    description: Sets time to midnight.
  yggdrasil.cmd.speed:
    description: Set a your speed.
  yggdrasil.cmd.speed.others:
    description: Set a player's speed.
